export const MAIN_PAGE = "/"

export const AUTH_PAGE = "/auth"
export const SIGNUP_PAGE = "/auth/signup"
export const SIGNIN_PAGE = "/auth/signin"
export const CONTACT_PAGE = "/contact"
export const COURSE_PAGE = "/course"
export const COURSES_PAGE = "/courses"
export const PROFILE_PAGE = "/profile"

export const ADMIN_PAGE = "/admin"
export const BILLING_PAGE = ADMIN_PAGE + "/billing"
export const COMMENTS_PAGE = ADMIN_PAGE + "/comments"
export const STUDENTS_PAGE = ADMIN_PAGE + "/students"
export const USERS_PAGE = ADMIN_PAGE + "/users"
export const ADMINS_PAGE = ADMIN_PAGE + "/admins"
export const SETTINGS_PAGE = ADMIN_PAGE + "/settings"
export const FEEDBACK_PAGE = ADMIN_PAGE + "/feedback"

export const ADD_PAGE = ADMIN_PAGE + "/add"
export const EDIT_PAGE = ADMIN_PAGE + "/edit"
